// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blxyanebvxazyvqqybsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJseHlhbmVidnhhenl2cXF5YnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTk5NzAsImV4cCI6MjA1NTYzNTk3MH0.Z3XYijD_aPw6jIzR4d_NabfXu32BSL1fTxl0LeNAv4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);